name: Deploy

on:
  push:
    branches: [main]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Prisma
        working-directory: ./api/prisma
        run: sudo go install github.com/prisma/prisma-client-go && go run github.com/prisma/prisma-client-go db push

      - name: Install the dependencies
        working-directory: ./api
        run: sudo go get

      - name: Build
        working-directory: ./api
        run: sudo go build

      - name: Restart PMGO
        run: sudo pmgo restart hits-api
